### ISSUE TITLE
这个代码怎么使用呀！

### ISSUE THREAD

**Issue by 7788kdd** [Yaoshicn/decaptcha#1]
我是一名大学生请问这份代码怎么使用呀！

**Comment by Yaoshicn** [comment]
好巧，我也是。

**Comment by 7788kdd** [comment]
你写了步骤，我觉得你应该写一份文件的说明，我看了半天代码才知道怎么用。哈哈

**Comment by Yaoshicn** [comment]
你可以看一下《机器学习实战》，不用全部看，看前面相关的几章就可以了，这个代码的核心算法是参考那本书上的。

**Comment by 7788kdd** [comment]
嗯嗯，我去看下。哈哈，谢啦
